---
- name: Retrieve additional info for AI
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Set systemd facts
      ansible.builtin.set_fact:
        linux_service: "{{ input_linux_service | default('httpd') }}"

    - name: Check if httpd is running
      check_mode: true
      ansible.builtin.systemd_service:
        state: started
        name: "{{ linux_service }}"
      register: service_status

    - name: Check if httpd is running
      ansible.builtin.debug:
        msg: "{{ service_status }}"

    - name: Fail if service is running properly
      ansible.builtin.fail:
        msg: >
          The {{ linux_service }} service is already running correctly.
          No troubleshooting is needed. Current status shows service is active.
      when: not service_status.changed

    - name: Check if status of {{ linux_service }}
      ansible.builtin.debug:
        msg: "{{ service_status.status.ActiveState if service_status.status.ActiveState is defined else 'ActiveState not found' }}"

    - name: Retrieve last 5 lines of httpd logs
      ansible.builtin.command: journalctl -u httpd.service -n 5
      register: systemd_logs
      ignore_errors: true
      changed_when: false

    - name: Store httpd logs as a variable
      ansible.builtin.set_fact:
        systemd_log_output: "{{ systemd_logs.stdout }}"

    - name: Display systemd logs
      ansible.builtin.debug:
        msg: "{{ systemd_log_output }}"

    # - name: Set stats for next controller job
    #   ansible.builtin.set_stats:
    #     data:
    #       gpt_prompt: |
    #         ### Instructions:
    #         We have an issue on our Red Hat Enterprise Linux server with the {{ linux_service }} service.

    #         The {{ linux_service }} service will not start.
    #         Please help me troubleshoot this issue and get the service back online.

    #         Here are recent error logs: {{ systemd_log_output }}

    #         ### Response:
    #       max_tokens: 2000


    - name: Set Slack message
      ansible.builtin.set_fact:
        slack_message: >-
            Automation Controller job ID {{ hostvars.localhost.tower_job_id }}
            has failed.
            These are the failed logs from the managed_node
            {{ systemd_log_output }}
            Please investigate the failure on the Apache.

    - name: Notify Slack
      community.general.slack:
        token: "{{ token }}"
        msg: |
            ```
            {{ slack_message }}
            ```
        channel: '#ansiblefest-demo'
        color: good
        username: 'AnsibleFest-bot'
        link_names: 0
        parse: 'none'
