---
- name: Web app issue
  hosts: all
  sources:
   - ansible.eda.kafka:
       host: service1
       port: 9092
       topic: httpd-error-logs

  rules:
   - name: apache shutdown detected
     condition: event.body.message is match("shutting down")
     action:
       run_job_template:
        organization: "Default"
        name: "Demo Job Template"