---
- name: Create Job Template with Survey
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Set a fact with the LLM text
      ansible.builtin.set_fact:
        gpt_generated_prompt: "{{ gpt_response.json.choices[0].text }}"

    - name: Show the LLM response text
      ansible.builtin.debug:
        msg: "The LLM suggests: {{ gpt_generated_prompt }}"

    - name: Create Job Template
      awx.awx.job_template:
        name: "Lightspeed Generate"
        job_type: "run"
        inventory: "{{ input_inventory | default('Demo Inventory') }}"
        project: "{{ input_project | default('AI-EDA') }}"
        playbook: "{{ input_playbook | default('playbooks/lightspeed_generate.yml') }}"
        credential: "{{ input_credential | default('AAP') }}"
        survey_enabled: true
        survey_spec: "{{ lookup('template', playbook_dir + '/templates/survey.j2') }}"
        validate_certs: false
        execution_environment: "Default execution environment"
