---
- name: Create Job Template with Survey
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Set a fact with the LLM text
      ansible.builtin.set_fact:
        gpt_generated_prompt: "{{ gpt_response.json.choices[0].text }}"

    - name: Show the LLM response text
      ansible.builtin.debug:
        msg: "The LLM suggests: {{ gpt_generated_prompt }}"

    - name: Create Job Template
      ansible.controller.job_template:
        name: "🧠 Lightspeed Remediation Playbook Generator"
        job_type: "run"
        inventory: "{{ input_inventory | default('Demo Inventory') }}"
        project: "{{ input_project | default('AI-EDA') }}"
        playbook: "{{ input_playbook | default('playbooks/lightspeed_generate.yml') }}"
        credentials:
          - "{{ input_credential | default('AAP') }}"
          - "{{ vault_credential | default('ansible-vault') }}"
        survey_enabled: true
        survey_spec: "{{ lookup('template', playbook_dir + '/templates/survey.j2') }}"
        validate_certs: true
        execution_environment: "Default execution environment"
        extra_vars:
          lightspeed_wca_token: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            31326239386334643138626532643162376537393064643933653330306438633632323166356566
            6439393932306536363037393466613362633636343931330a386232363331376534353865373935
            38373836333463326565346331356635653261666233663230646239393939373461636266336532
            6332383564336662620a633533633563393561663165646265323830373637623161663039323936
            65343033613239613232663664643263386432373632323965343330626366373236
