---
- name: Print out facts for debugging
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:

    - name: Print out all hostvars facts
      ansible.builtin.debug:
        var: hostvars.localhost
