---
- name: Add bad directive under in Apache configuration
  hosts: node1
  become: true
  tasks:
    - name: Ensure Apache is installed
      ansible.builtin.dnf:
        name: httpd
        state: present
      notify:
        - Restart apache

    - name: Maintain httpd.conf
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^InvalidDirectiveHere$'
        state: absent
      notify:
        - Restart apache

  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted
      register: httpd_restart_result
      failed_when: "'Job for httpd.service failed' not in httpd_restart_result.msg | default('')"
