---
- name: Add bad directive under in Apache configuration
  hosts: node1
  become: true
  tasks:
    - name: Ensure Apache is installed
      ansible.builtin.dnf:
        name: httpd
        state: present
      tags:
        - always
      notify:
        - Restart apache

    - name: Add InvalidDirectiveHere
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        insertafter: '^ServerRoot'
        line: 'InvalidDirectiveHere'
        state: present
      tags:
        - never
        - break
      notify:
        - Restart apache

    - name: Maintain httpd.conf
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^InvalidDirectiveHere$'  # Matches the line exactly
        state: absent
      tags:
        - never
        - restore
      notify:
        - Restart apache

  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted
      register: httpd_restart_result
      failed_when: "'Job for httpd.service failed' not in httpd_restart_result.msg | default('')"
