---
- name: Interact with Ansible Lightspeed API and Generate Ansible Playbook
  hosts: localhost
  gather_facts: false
  vars_files:
    - ls_vars.yml
  tasks:
    - name: Send request to AI API
      ansible.builtin.uri:
        url: "{{ input_lightspeed_url | default('https://c.ai.ansible.redhat.com/api/v0/ai/generations/') }}"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ lightspeed_wca_token }}"
        body_format: json
        body:
          text: "{{ lightspeed_prompt }}"
      register: response
      no_log: true

    - name: Display API response
      ansible.builtin.debug:
        msg: "{{ response.json }}"

    - name: Set fact for Ansible Lightspeed generated playbook
      ansible.builtin.set_fact:
        lightspeed_playbook: "{{ response.json.playbook | from_yaml }}"

    - name: Set stat on lightspeed_playbook
      ansible.builtin.set_stats:
        data:
          lightspeed_playbook: "{{ lightspeed_playbook }}"

    - name: Display Ansible Playbook in JSON
      ansible.builtin.debug:
        msg: "{{ lightspeed_playbook }}"

    - name: Display Ansible Playbook in YAML
      ansible.builtin.debug:
        msg: "{{ lightspeed_playbook | to_nice_yaml(sort_keys=False) }}"
