---
- name: Interact with Ansible Lightspeed API and Generate Ansible Playbook
  hosts: localhost
  gather_facts: false
  vars:
    lightspeed_prompt: "Remove line that contains InvalidDirectiveHere from /etc/httpd/conf/httpd.conf and restart httpd"
  tasks:
    - name: Set vaulted token
      ansible.builtin.set_fact
        lightspeed_wca_token: !vault |
                  $ANSIBLE_VAULT;1.1;AES256
                  32643533616234383934383766393235393936643061656236316264323330633636663664363835
                  6137396566383466323662306237653635356465626635640a623636326461613238643363396562
                  66336264616334386430336337356165616662636362373365343533313238393431666563663734
                  3362326162366531620a376333643362636161383830373431386134316333323539623937643961
                  36393538373261306162366532623464383834663134643063316561393436396231
    - name: Send request to AI API
      ansible.builtin.uri:
        url: "{{ input_lightspeed_url | default('https://c.ai.ansible.redhat.com/api/v0/ai/generations/') }}"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ lightspeed_wca_token }}"
        body_format: json
        body:
          text: "{{ lightspeed_prompt }}"
      register: response

    - name: Display API response
      ansible.builtin.debug:
        msg: "{{ response.json }}"

    - name: Set fact for Ansible Lightspeed generated playbook
      ansible.builtin.set_fact:
        lightspeed_playbook: "{{ response.json.playbook | from_yaml }}"

    - name: Set stat on lightspeed_playbook
      ansible.builtin.set_stats:
        data:
          lightspeed_playbook: "{{ lightspeed_playbook }}"

    - name: Display Ansible Playbook in JSON
      ansible.builtin.debug:
        msg: "{{ lightspeed_playbook }}"

    - name: Display Ansible Playbook in YAML
      ansible.builtin.debug:
        msg: "{{ lightspeed_playbook | to_nice_yaml(sort_keys=False) }}"
