- name: Create lightspeed_playbooks repository on Gitea
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Set input vars
      ansible.builtin.set_fact:
        repo_name: "{{ input_repo_name | default('lightspeed_playbooks') }}"
        repo_description: "{{ input_repo_description | default('Repository for Lightspeed Ansible Playbooks') }}"
    - name: Retrieve a repository from a distant location and make it available locally
      ansible.scm.git_retrieve:
        branch:
          duplicate_detection: false
          name: main
        origin:
          url: "{{ gitea_url }}/lab-user/{{ repo_name }}.git"
          token: "{{ gitea_token }}"
      register: repository
  
    - name: Update 'hosts' to 'all' if it's not already 'all' or 'node1'
      ansible.builtin.set_fact:
        lightspeed_playbook: >-
          {{
            lightspeed_playbook
            if (lightspeed_playbook is search('(?m)^\\s*hosts:\\s*(all|node1)\\s*$'))
            else (lightspeed_playbook | regex_replace('(?m)^\\s*hosts:\\s*.*$', '  hosts: all'))
          }}

    # Don't deserialize – just save the raw YAML string
    - name: Save formatted YAML response to file (preserve key order)
      ansible.builtin.copy:
        content: "{{ lightspeed_playbook }}"
        dest: "{{ repository['path'] }}/lightspeed-response.yml"
        mode: '0644'

    - name: Publish the changes
      ansible.scm.git_publish:
        path: "{{ repository['path'] }}"
        token: "{{ gitea_token }}"
