- name: Create lightspeed_playbooks repository on Gitea
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Set input vars
      ansible.builtin.set_fact:
        gitea_url: "https://bastion.cj4kg.sandbox897.opentlc.com:488"  # Replace with your Gitea URL
        repo_name: "{{ input_repo_name | default('lightspeed_playbooks') }}"
        repo_description: "{{ input_repo_description | default('Repository for Lightspeed Ansible Playbooks') }}"
        gitea_username: "{{ input_gitea_username | default('lab-user') }}"
        gitea_password: "{{ input_gitea_password | default('MjQ5NDQx_1') }}"
    - name: Retrieve a repository from a distant location and make it available locally
      ansible.scm.git_retrieve:
        branch:
          duplicate_detection: false
          name: main
        origin:
          url: "{{ gitea_url }}/lab-user/{{ repo_name }}.git"
          token: "{{ gitea_token_sha1 }}"
      register: repository        
    - name: Save formatted YAML response to file
      ansible.builtin.copy:
        content: "{{ lightspeed_playbook | to_nice_yaml(sort_keys=False) }}"
        dest: "{{ repository['path'] }}/lightspeed-response.yml"
        mode: '0644'
    - name: Publish the changes
      ansible.scm.git_publish:
        path: "{{ repository['path'] }}"
        token: "{{ gitea_token_sha1 }}"